### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by DenSwitch** [scmanjarrez/Genshin-Impact-Stats-Telegram-Bot#2]
hi. could you add teapot currency, parametric transformer and expeditions notification, please? 
also, i think it would be great to make resin notification configurable (manually set resin to notify using setting or at least value in config, not 150+ only). for example, you can send "/notify 40" and bot will send you message when your resin is 40, if you used resin and don't set "/notify", it notifies when resin reaches value that is provided in config/settings. 
and add option to set info updating time, please!
thanks a lot

**Comment by scmanjarrez** [comment]
Some of the features were in my last bot [Genshin-Impact-Resin-Tracker-Telegram-Bot](https://github.com/scmanjarrez/Genshin-Impact-Resin-Tracker-Telegram-Bot), when I created this one using Hoyoverse api, some data were unavailable at that time so I just removed them. I'll try to re-implement them. Also, what do you mean by "option to set info updating time"?

**Comment by DenSwitch** [comment]
> what do you mean by "option to set info updating time"?

i mean ability to set the frequency of data updates. like 10 minutes, 30 minutes etc.

**Comment by scmanjarrez** [comment]
I have added the features you suggested, check [extra_notifications](https://github.com/scmanjarrez/Genshin-Impact-Stats-Telegram-Bot/tree/extra_notifications) branch. Teapot currency is a bit awkward due to low updates from the genshin API. I won't merge it to master for the time being until enough testing is done. 
There is a new command: /set <type> <value>, that can be used to change the resin and teapot currency threshold, and the notes interval update. Check /help output. Also, there is a new button in the /menu to enable/disable notifications for resin/teapot/parametric and expeditions (triggers only when the longer expedition is completed, not for each expedition completed)

**Comment by DenSwitch** [comment]
great, i will test it and write back if something is wrong. thanks a lot!
